#ifndef __GAME_PLAY_GRID_MATRIX__H
#define __GAME_PLAY_GRID_MATRIX__H

#define GAME_PLAY_GRID_MATRIX_HEIGHT (20)
#define GAME_PLAY_GRID_MATRIX_WIDTH (20)
#define GAME_PLAY_GRID_MATRIX_START_POS_X (5)
#define GAME_PLAY_GRID_MATRIX_START_POS_Y (12)

#endif /* __GAME_PLAY_GRID_MATRIX__H */