#ifndef __GAME_PLAY_GRID_MATRIX__H
#define __GAME_PLAY_GRID_MATRIX__H

#include "game/game_play/physics/game_board.h"

#define GAME_PLAY_GRID_MATRIX_HEIGHT (GAME_PLAY_BOARD_HEIGHT + 2)
#define GAME_PLAY_GRID_MATRIX_WIDTH (GAME_PLAY_BOARD_WIDTH + 2)

#define GAME_PLAY_GRID_MATRIX_START_POS_X_IN_WPRINT (GAME_PLAY_BOARD_START_POS_X_IN_WPRINT - 1)
#define GAME_PLAY_GRID_MATRIX_START_POS_Y_IN_WPRINT (GAME_PLAY_BOARD_START_POS_Y_IN_WPRINT - 1)

#endif /* __GAME_PLAY_GRID_MATRIX__H */