#ifndef __GAME_PLAY_BOARD_FRAME__H
#define __GAME_PLAY_BOARD_FRAME__H

#include "tetris/physics/game_board.h"

#define GAME_PLAY_BOARD_FRAME_HEIGHT (GAME_PLAY_BOARD_HEIGHT + 2)
#define GAME_PLAY_BOARD_FRAME_WIDTH (GAME_PLAY_BOARD_WIDTH + 2)

#define GAME_PLAY_BOARD_FRAME_START_POS_X_WPRINT (GAME_PLAY_BOARD_START_POS_X_WPRINT - 1)
#define GAME_PLAY_BOARD_FRAME_START_POS_Y_WPRINT (GAME_PLAY_BOARD_START_POS_Y_WPRINT - 1)

#endif /* __GAME_PLAY_BOARD_FRAME__H */