#ifndef __TETRIS_PLAY_BOARD_FRAME__H
#define __TETRIS_PLAY_BOARD_FRAME__H

#include "tetris/physics/tetris_play_board.h"

#define TETRIS_PLAY_BOARD_FRAME_HEIGHT (TETRIS_PLAY_BOARD_HEIGHT + 2)
#define TETRIS_PLAY_BOARD_FRAME_WIDTH (TETRIS_PLAY_BOARD_WIDTH + 2)

#define TETRIS_PLAY_BOARD_FRAME_START_POS_X_WPRINT (TETRIS_PLAY_BOARD_START_POS_X_WPRINT - 1)
#define TETRIS_PLAY_BOARD_FRAME_START_POS_Y_WPRINT (TETRIS_PLAY_BOARD_START_POS_Y_WPRINT - 1)

#endif /* __TETRIS_PLAY_BOARD_FRAME__H */