#ifndef __TETRIS_PLAY_SCREEN__H
#define __TETRIS_PLAY_SCREEN__H

#define TETRIS_PLAY_SINGLE_SCREEN_HEIGHT_WPRINT (32)
#define TETRIS_PLAY_SINGLE_SCREEN_WIDTH_WPRINT (46)

#define TETRIS_PLAY_SINGLE_SCREEN_START_POS_X_WPRINT (0)
#define TETRIS_PLAY_SINGLE_SCREEN_START_POS_Y_WPRINT (0)

#endif /* __TETRIS_PLAY_SCREEN__H */