#ifndef __TETRIS_PLAY_SCREEN__H
#define __TETRIS_PLAY_SCREEN__H

#define TETRIS_PLAY_SINGLE_SCREEN_HEIGHT_WPRINT (32 + 2)
#define TETRIS_PLAY_SINGLE_SCREEN_WIDTH_WPRINT (46 + 2 * 10)

#define TETRIS_PLAY_SINGLE_SCREEN_POS_X (0)
#define TETRIS_PLAY_SINGLE_SCREEN_POS_Y (0)

#define TETRIS_PLAY_SINGLE_SCREEN_POS_X_WPRINT TETRIS_PLAY_SINGLE_SCREEN_POS_X
#define TETRIS_PLAY_SINGLE_SCREEN_POS_Y_WPRINT TETRIS_PLAY_SINGLE_SCREEN_POS_Y

#endif /* __TETRIS_PLAY_SCREEN__H */