#ifndef __GAME_PLAY_SCREEN__H
#define __GAME_PLAY_SCREEN__H

#define GAME_PLAY_SCREEN_HEIGHT (30)
#define GAME_PLAY_SCREEN_WIDTH (44)
#define GAME_PLAY_SCREEN_START_POS_X (0)
#define GAME_PLAY_SCREEN_START_POS_Y (0)

#endif /* __GAME_PLAY_SCREEN__H */