#ifndef __GAME_PLAY_SCREEN__H
#define __GAME_PLAY_SCREEN__H

#define GAME_PLAY_SINGLE_SCREEN_HEIGHT_IN_WPRINT (32)
#define GAME_PLAY_SINGLE_SCREEN_WIDTH_IN_WPRINT (46)

#define GAME_PLAY_SINGLE_SCREEN_START_POS_X_IN_WPRINT (0)
#define GAME_PLAY_SINGLE_SCREEN_START_POS_Y_IN_WPRINT (0)

#endif /* __GAME_PLAY_SCREEN__H */