#ifndef __GAME_MANAGER__H
#define __GAME_MANAGER__H

#include "game/game_play/ui/game_play_screen.h"

#define GAME_CONSOLE_STDOUT_POS_X (GAME_PLAY_SINGLE_SCREEN_START_POS_X_IN_WPRINT + GAME_PLAY_SINGLE_SCREEN_HEIGHT_IN_WPRINT + 1)
#define GAME_CONSOLE_STDOUT_POS_Y (0)

#define GAME_CONSOLE_STDERR_POS_X (GAME_PLAY_SINGLE_SCREEN_START_POS_X_IN_WPRINT)
#define GAME_CONSOLE_STDERR_POS_Y (GAME_PLAY_SINGLE_SCREEN_START_POS_Y_IN_WPRINT + GAME_PLAY_SINGLE_SCREEN_WIDTH_IN_WPRINT + 5)

void run_game_manager(void);

#endif /* __GAME_MANAGER__H */