#ifndef __GAME_SYSTEM_MANAGER__H
#define __GAME_SYSTEM_MANAGER__H

#include "tetris/scene/tetris_play_screen.h"

//#define CONSOLE_STDOUT_POS_X (TETRIS_PLAY_SINGLE_SCREEN_START_POS_X_WPRINT + GAME_PLAY_SINGLE_SCREEN_HEIGHT_WPRINT + 1)
//#define CONSOLE_STDOUT_POS_Y (0)

//#define CONSOLE_STDERR_POS_X (TETRIS_PLAY_SINGLE_SCREEN_START_POS_X_WPRINT)
//#define CONSOLE_STDERR_POS_Y (TETRIS_PLAY_SINGLE_SCREEN_START_POS_Y_WPRINT + GAME_PLAY_SINGLE_SCREEN_WIDTH_WPRINT + 5)

void run_game_system_manager(void);

#endif /* __GAME_SYSTEM_MANAGER__H */